---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary
  namespace: metallb
spec:
  addresses:
    - 172.30.1.101-172.30.1.200 # ✅ 사용할 아이피 대역 범위
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: primary
  namespace: metallb
spec:
  ipAddressPools:
    - primary
