name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행
      - develop

jobs:
  build:
    name: Build & Push to Harbor
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Git 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Docker 로그인 (Harbor)
      - name: Login to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.moizago.store -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      # 3️⃣ Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t harbor.moizago.store/nextjs/moizago-app:${{ github.sha }} .
          docker tag harbor.moizago.store/nextjs/moizago:${{ github.sha }} harbor.moizago.store/nextjs/moizago-app:latest

      # 4️⃣ Harbor에 Docker 이미지 푸시
      - name: Push Docker Image to Harbor
        run: |
          docker push harbor.moizago.store/nextjs/moizago-app:${{ github.sha }}
          docker push harbor.moizago.store/nextjs/moizago-app:latest

      # 5️⃣ GitOps 저장소(`nextjs-k8s-manifests.git`) 업데이트
      - name: Update Kubernetes Deployment YAML
        run: |
          git config --global user.email "devbluemoons@gmail.com"
          git config --global user.name "moonblue"
          git clone https://${{ secrets.GH_PAT }}@github.com/YOUR_GITHUB_ORG/nextjs-k8s-manifests.git
          cd nextjs-k8s-manifests
          sed -i "s|image: harbor.moizago.stor/nextjs/moizago-app:.*|image: harbor.moizago.store/nextjs/moizago-app:${{ github.sha }}|g" values.yaml
          git add values.yaml
          git commit -m "Update Next.js image to ${{ github.sha }}"
          git push origin main
